# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import buffer_pb2 as buffer__pb2


class BufferServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushTransition = channel.unary_unary(
                '/rl.buffer.BufferService/PushTransition',
                request_serializer=buffer__pb2.PushRequest.SerializeToString,
                response_deserializer=buffer__pb2.Status.FromString,
                )
        self.SampleBatch = channel.unary_unary(
                '/rl.buffer.BufferService/SampleBatch',
                request_serializer=buffer__pb2.SampleRequest.SerializeToString,
                response_deserializer=buffer__pb2.Batch.FromString,
                )


class BufferServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushTransition(self, request, context):
        """Use wrapper message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SampleBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BufferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushTransition': grpc.unary_unary_rpc_method_handler(
                    servicer.PushTransition,
                    request_deserializer=buffer__pb2.PushRequest.FromString,
                    response_serializer=buffer__pb2.Status.SerializeToString,
            ),
            'SampleBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SampleBatch,
                    request_deserializer=buffer__pb2.SampleRequest.FromString,
                    response_serializer=buffer__pb2.Batch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.buffer.BufferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BufferService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushTransition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rl.buffer.BufferService/PushTransition',
            buffer__pb2.PushRequest.SerializeToString,
            buffer__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SampleBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rl.buffer.BufferService/SampleBatch',
            buffer__pb2.SampleRequest.SerializeToString,
            buffer__pb2.Batch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
