# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x02rl\"\x07\n\x05\x45mpty\"%\n\x06Status\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xdf\x01\n\x10\x45xperimentConfig\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\x12\x10\n\x08\x65nv_name\x18\x02 \x01(\t\x12\x0c\n\x04seed\x18\x03 \x01(\x05\x12\x11\n\tmax_steps\x18\x04 \x01(\x05\x12\x11\n\talgorithm\x18\x05 \x01(\t\x12:\n\x0bhyperparams\x18\x06 \x03(\x0b\x32%.rl.ExperimentConfig.HyperparamsEntry\x1a\x32\n\x10HyperparamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9a\x01\n\nTransition\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\x0c\x12\x0e\n\x06reward\x18\x04 \x01(\x02\x12\x12\n\nnext_state\x18\x05 \x01(\x0c\x12\x0c\n\x04\x64one\x18\x06 \x01(\x08\x12\x0c\n\x04step\x18\x07 \x01(\x03\x12\x16\n\x0epolicy_version\x18\x08 \x01(\x05\",\n\x05\x42\x61tch\x12#\n\x0btransitions\x18\x01 \x03(\x0b\x32\x0e.rl.Transition\"A\n\x06Policy\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x0f\n\x07weights\x18\x03 \x01(\x0c\"g\n\x07Metrics\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\x12\x13\n\x0bsource_node\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x13\n\x0bmetric_name\x18\x04 \x01(\t\x12\x0c\n\x04step\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXPERIMENTCONFIG_HYPERPARAMSENTRY']._options = None
  _globals['_EXPERIMENTCONFIG_HYPERPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_STATUS']._serialized_start=29
  _globals['_STATUS']._serialized_end=66
  _globals['_EXPERIMENTCONFIG']._serialized_start=69
  _globals['_EXPERIMENTCONFIG']._serialized_end=292
  _globals['_EXPERIMENTCONFIG_HYPERPARAMSENTRY']._serialized_start=242
  _globals['_EXPERIMENTCONFIG_HYPERPARAMSENTRY']._serialized_end=292
  _globals['_TRANSITION']._serialized_start=295
  _globals['_TRANSITION']._serialized_end=449
  _globals['_BATCH']._serialized_start=451
  _globals['_BATCH']._serialized_end=495
  _globals['_POLICY']._serialized_start=497
  _globals['_POLICY']._serialized_end=562
  _globals['_METRICS']._serialized_start=564
  _globals['_METRICS']._serialized_end=667
# @@protoc_insertion_point(module_scope)
