# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: environment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'environment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65nvironment.proto\x12\x02rl\x1a\x0c\x63ommon.proto2\xa7\x01\n\x12\x45nvironmentService\x12.\n\nInitialize\x12\x14.rl.ExperimentConfig\x1a\n.rl.Status\x12\x30\n\x0cStartRollout\x12\x14.rl.ExperimentConfig\x1a\n.rl.Status\x12/\n\x0bStopRollout\x12\x14.rl.ExperimentConfig\x1a\n.rl.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'environment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVIRONMENTSERVICE']._serialized_start=40
  _globals['_ENVIRONMENTSERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
