# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2
import policy_pb2 as policy__pb2


class PolicyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPolicy = channel.unary_unary(
                '/rl.PolicyService/GetPolicy',
                request_serializer=policy__pb2.PolicyRequest.SerializeToString,
                response_deserializer=common__pb2.Policy.FromString,
                )
        self.UpdatePolicy = channel.unary_unary(
                '/rl.PolicyService/UpdatePolicy',
                request_serializer=common__pb2.Policy.SerializeToString,
                response_deserializer=common__pb2.Status.FromString,
                )
        self.GetPolicyVersion = channel.unary_unary(
                '/rl.PolicyService/GetPolicyVersion',
                request_serializer=policy__pb2.PolicyRequest.SerializeToString,
                response_deserializer=common__pb2.Policy.FromString,
                )


class PolicyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPolicy(self, request, context):
        """Actors fetch latest weights
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Learner pushes new weights
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicyVersion(self, request, context):
        """Query current version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=policy__pb2.PolicyRequest.FromString,
                    response_serializer=common__pb2.Policy.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=common__pb2.Policy.FromString,
                    response_serializer=common__pb2.Status.SerializeToString,
            ),
            'GetPolicyVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicyVersion,
                    request_deserializer=policy__pb2.PolicyRequest.FromString,
                    response_serializer=common__pb2.Policy.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PolicyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rl.PolicyService/GetPolicy',
            policy__pb2.PolicyRequest.SerializeToString,
            common__pb2.Policy.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rl.PolicyService/UpdatePolicy',
            common__pb2.Policy.SerializeToString,
            common__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPolicyVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rl.PolicyService/GetPolicyVersion',
            policy__pb2.PolicyRequest.SerializeToString,
            common__pb2.Policy.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
