# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analytics.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\x0crl.analytics\"g\n\x07Metrics\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\x12\x13\n\x0bsource_node\x18\x02 \x01(\t\x12\x13\n\x0bmetric_name\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\x12\x0c\n\x04step\x18\x05 \x01(\x03\"\x14\n\x06Status\x12\n\n\x02ok\x18\x01 \x01(\x08\":\n\x0cQueryRequest\x12\x15\n\rexperiment_id\x18\x01 \x01(\t\x12\x13\n\x0bmetric_name\x18\x02 \x01(\t\"4\n\nMetricList\x12&\n\x07metrics\x18\x01 \x03(\x0b\x32\x15.rl.analytics.Metrics2\x96\x01\n\x10\x41nalyticsService\x12<\n\rReportMetrics\x12\x15.rl.analytics.Metrics\x1a\x14.rl.analytics.Status\x12\x44\n\x0cQueryMetrics\x12\x1a.rl.analytics.QueryRequest\x1a\x18.rl.analytics.MetricListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_METRICS']._serialized_start=33
  _globals['_METRICS']._serialized_end=136
  _globals['_STATUS']._serialized_start=138
  _globals['_STATUS']._serialized_end=158
  _globals['_QUERYREQUEST']._serialized_start=160
  _globals['_QUERYREQUEST']._serialized_end=218
  _globals['_METRICLIST']._serialized_start=220
  _globals['_METRICLIST']._serialized_end=272
  _globals['_ANALYTICSSERVICE']._serialized_start=275
  _globals['_ANALYTICSSERVICE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
