# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import analytics_pb2 as analytics__pb2


class AnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportMetrics = channel.unary_unary(
                '/rl.analytics.AnalyticsService/ReportMetrics',
                request_serializer=analytics__pb2.Metrics.SerializeToString,
                response_deserializer=analytics__pb2.Status.FromString,
                )
        self.QueryMetrics = channel.unary_unary(
                '/rl.analytics.AnalyticsService/QueryMetrics',
                request_serializer=analytics__pb2.QueryRequest.SerializeToString,
                response_deserializer=analytics__pb2.MetricList.FromString,
                )


class AnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReportMetrics(self, request, context):
        """Called by other services to report metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMetrics(self, request, context):
        """Called by Experiment Service to fetch aggregated metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMetrics,
                    request_deserializer=analytics__pb2.Metrics.FromString,
                    response_serializer=analytics__pb2.Status.SerializeToString,
            ),
            'QueryMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMetrics,
                    request_deserializer=analytics__pb2.QueryRequest.FromString,
                    response_serializer=analytics__pb2.MetricList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl.analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rl.analytics.AnalyticsService/ReportMetrics',
            analytics__pb2.Metrics.SerializeToString,
            analytics__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rl.analytics.AnalyticsService/QueryMetrics',
            analytics__pb2.QueryRequest.SerializeToString,
            analytics__pb2.MetricList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
