# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buffer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62uffer.proto\x12\trl.buffer\"]\n\nTransition\x12\r\n\x05state\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0e\n\x06reward\x18\x03 \x01(\x02\x12\x12\n\nnext_state\x18\x04 \x01(\t\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\"8\n\x0bPushRequest\x12)\n\ntransition\x18\x01 \x01(\x0b\x32\x15.rl.buffer.Transition\"#\n\rSampleRequest\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\"3\n\x05\x42\x61tch\x12*\n\x0btransitions\x18\x01 \x03(\x0b\x32\x15.rl.buffer.Transition\"\x14\n\x06Status\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x87\x01\n\rBufferService\x12;\n\x0ePushTransition\x12\x16.rl.buffer.PushRequest\x1a\x11.rl.buffer.Status\x12\x39\n\x0bSampleBatch\x12\x18.rl.buffer.SampleRequest\x1a\x10.rl.buffer.Batchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buffer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSITION']._serialized_start=27
  _globals['_TRANSITION']._serialized_end=120
  _globals['_PUSHREQUEST']._serialized_start=122
  _globals['_PUSHREQUEST']._serialized_end=178
  _globals['_SAMPLEREQUEST']._serialized_start=180
  _globals['_SAMPLEREQUEST']._serialized_end=215
  _globals['_BATCH']._serialized_start=217
  _globals['_BATCH']._serialized_end=268
  _globals['_STATUS']._serialized_start=270
  _globals['_STATUS']._serialized_end=290
  _globals['_BUFFERSERVICE']._serialized_start=293
  _globals['_BUFFERSERVICE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
