# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: learner.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlearner.proto\x12\x02rl\x1a\x0c\x63ommon.proto2\xa7\x01\n\x0eLearnerService\x12.\n\nInitialize\x12\x14.rl.ExperimentConfig\x1a\n.rl.Status\x12-\n\tTrainStep\x12\x14.rl.ExperimentConfig\x1a\n.rl.Status\x12\x36\n\x11GetTrainingStatus\x12\x14.rl.ExperimentConfig\x1a\x0b.rl.Metricsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'learner_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LEARNERSERVICE']._serialized_start=36
  _globals['_LEARNERSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
