# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: policy.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpolicy.proto\x12\x02rl\x1a\x0c\x63ommon.proto\"&\n\rPolicyRequest\x12\x15\n\rexperiment_id\x18\x01 \x01(\t2\x96\x01\n\rPolicyService\x12*\n\tGetPolicy\x12\x11.rl.PolicyRequest\x1a\n.rl.Policy\x12&\n\x0cUpdatePolicy\x12\n.rl.Policy\x1a\n.rl.Status\x12\x31\n\x10GetPolicyVersion\x12\x11.rl.PolicyRequest\x1a\n.rl.Policyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'policy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POLICYREQUEST']._serialized_start=34
  _globals['_POLICYREQUEST']._serialized_end=72
  _globals['_POLICYSERVICE']._serialized_start=75
  _globals['_POLICYSERVICE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
